// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdoqNx0mFp87JxYOz3SgeuwbibkAGc1uU',
    appId: '1:1071136211941:web:ac87e125459070f032a50c',
    messagingSenderId: '1071136211941',
    projectId: 'sana-mobile-783d3',
    authDomain: 'sana-mobile-783d3.firebaseapp.com',
    storageBucket: 'sana-mobile-783d3.appspot.com',
    measurementId: 'G-JSB8JKJ5KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArybllCBf2W3wkCoD3fHxDJjg-J-bV3GQ',
    appId: '1:1071136211941:android:2bb7c0bb3c655e8732a50c',
    messagingSenderId: '1071136211941',
    projectId: 'sana-mobile-783d3',
    storageBucket: 'sana-mobile-783d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswjotJNo8SpfJbn84DAHHmttwobNXK_A',
    appId: '1:1071136211941:ios:e2308f13e8d6956c32a50c',
    messagingSenderId: '1071136211941',
    projectId: 'sana-mobile-783d3',
    storageBucket: 'sana-mobile-783d3.appspot.com',
    iosBundleId: 'com.example.sanaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswjotJNo8SpfJbn84DAHHmttwobNXK_A',
    appId: '1:1071136211941:ios:e2308f13e8d6956c32a50c',
    messagingSenderId: '1071136211941',
    projectId: 'sana-mobile-783d3',
    storageBucket: 'sana-mobile-783d3.appspot.com',
    iosBundleId: 'com.example.sanaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdoqNx0mFp87JxYOz3SgeuwbibkAGc1uU',
    appId: '1:1071136211941:web:b3fc6997c158e57c32a50c',
    messagingSenderId: '1071136211941',
    projectId: 'sana-mobile-783d3',
    authDomain: 'sana-mobile-783d3.firebaseapp.com',
    storageBucket: 'sana-mobile-783d3.appspot.com',
    measurementId: 'G-CHXPSEHY1P',
  );

}